export const APP_REPOSITORIES = {
  USER: 'APP_REPOSITORIES.USER',
  WALLET: 'APP_REPOSITORIES.WALLET',
  TRANSACTION: 'APP_REPOSITORIES.TRANSACTION',
  OTP_VERIFICATION: 'APP_REPOSITORIES.OTP_VERIFICATION',
} as const;
